class ResourceList{
  static List<String> storiesList = [
    "ফেলুদার গোয়েন্দাগিরি.pdf",
    "বাদশাহী আংটি.pdf",
    "কৈলাস চৌধুরীর পাথর.pdf",
    "শেয়াল দেবতা রহস্য.pdf",
    "গ্যাংটকে গন্ডগোল.pdf",
    "সোনার কেল্লা.pdf",
    "বাক্স রহস্য.pdf",
    "সমাদ্দারের চাবি.pdf",
    "কৈলাসে কেলেঙ্কারি.pdf",
    "রয়েল বেঙ্গল রহস্য.pdf",
    "জয় বাবা ফেলুনাথ.pdf",
    "ঘুরঘুটিয়ার ঘটনা.pdf",
    "বোম্বাইয়ের বোম্বেটে.pdf",
    "গোঁসাইপুর সরগরম.pdf",
    "গোরস্থানে সাবধান.pdf",
    "ছিন্নমস্তার অভিশাপ.pdf",
    "হত্যাপুরী.pdf",
    "গোলকধাম রহস্য.pdf",
    "যত কাণ্ড কাঠমান্ডুতে.pdf",
    "নেপোলিয়নের চিঠি.pdf",
    "টিনটোরেটোর যীশু.pdf",
    "অম্বর সেন অন্তর্ধান রহস্য.pdf",
    "জাহাঙ্গীরের স্বর্ণমুদ্রা.pdf",
    "এবার কাণ্ড কেদারনাথে.pdf",
    "বোসপুকুরে খুনখারাপি.pdf",
    "দার্জিলিং জমজমাট.pdf",
    "ভূস্বর্গ ভয়ংকর.pdf",
    "অপ্সরা থিয়েটারের মামলা.pdf",
    "শকুন্তলার কণ্ঠহার.pdf",
    "গোলাপি মুক্তা রহস্য.pdf",
    "লন্ডনে ফেলুদা.pdf",
    "ডাঃ মুনশির ডায়েরি.pdf",
    "নয়ন রহস্য.pdf",
    "রবার্টসনের রুবি.pdf",
    "ইন্দ্রজাল রহস্য.pdf",
  ];

  static List<String> yearList = ['65', '66', '67', '70', '70', '71', '72', '73', '74', '74','75', '75', '76', '76', '77', '78', '79', '80', '80', '81','82', '83', '83', '84', '85', '86', '87', '87', '88', '89','89', '90', '90', '92', '96',];
  static List<String> imageList = [
    "assets/launcher/f1.jpg",
    "assets/launcher/f2.jpg",
    "assets/launcher/f3.jpg",
    "assets/launcher/f4.jpg",
    "assets/launcher/f5.jpg",
    "assets/launcher/f6.jpg",
    "assets/launcher/f7.jpg",
    "assets/launcher/f8.jpg",
    "assets/launcher/f9.jpg",
    "assets/launcher/f10.jpg",
    "assets/launcher/f11.jpg",
    "assets/launcher/f12.jpg",
    "assets/launcher/f13.jpg",
    "assets/launcher/f14.jpg",
    "assets/launcher/f15.jpg",
    "assets/launcher/f16.jpg",
    "assets/launcher/f17.jpg",
    "assets/launcher/f18.jpg",
    "assets/launcher/f19.jpg",
    "assets/launcher/f20.jpg",
    "assets/launcher/f21.jpg",
    "assets/launcher/f22.jpg",
    "assets/launcher/f23.jpg",
    "assets/launcher/f24.jpg",
    "assets/launcher/f25.jpg",
    "assets/launcher/f26.jpg",
    "assets/launcher/f27.jpg",
    "assets/launcher/f28.jpg",
    "assets/launcher/f29.jpg",
    "assets/launcher/f30.jpg",
    "assets/launcher/f31.jpg",
    "assets/launcher/f32.jpg",
    "assets/launcher/f33.jpg",
    "assets/launcher/f34.jpg",
    "assets/launcher/f35.jpg",
  ];
}