class ResourceList{
  static List<String> storiesList = [
    "Feludar Goendagiri.pdf",
    "Badshahi Angti.pdf",
    "Kailash Chowdhury'r Pathar.pdf",
    "Sheyal Debota Rahasya.pdf",
    "Gangtokey Gondogol.pdf",
    "Sonar Kella.pdf",
    "Baksho Rahashya.pdf",
    "Samaddarer Chabi.pdf",
    "Kailashey Kelenkari.pdf",
    "Royal Bengal Rahashya.pdf",
    "Joi Baba Felunath.pdf",
    "Ghurghutiyar Ghatona.pdf",
    "Bombaiyer Bombete.pdf",
    "Gosainpur Sargaram.pdf",
    "Gorosthaney Sabdhan.pdf",
    "Chhinnamastar Abhishap.pdf",
    "Hatyapuri.pdf",
    "Golokdham Rahasya.pdf",
    "Joto Kando Kathmandute.pdf",
    "Napoleoner Chithi.pdf",
    "Tintorettor Jishu.pdf",
    "Ambar Sen Antordhan Rahasya.pdf",
    "Jahangirer Swarnamudra.pdf",
    "Ebar Kando Kedarnathe.pdf",
    "Bosepukure Khunkharapi.pdf",
    "Darjeeling Jamjomat.pdf",
    "Bhuswargo Bhayankar.pdf",
    "Apsara Theaterer Mamla.pdf",
    "Shakuntalar Kanthahaar.pdf",
    "Golapi Mukta Rahasya.pdf",
    "Londone Feluda.pdf",
    "Dr. Munshir Diary.pdf",
    "Nayan Rahasya.pdf",
    "Robertsoner Ruby.pdf",
    "Indrajal Rahasya.pdf",
  ];
  static List<String> yearList = ['65', '66', '67', '70', '70', '71', '72', '73', '74', '74','75', '75', '76', '76', '77', '78', '79', '80', '80', '81','82', '83', '83', '84', '85', '86', '87', '87', '88', '89','89', '90', '90', '92', '96',];
  static List<String> imageList = [
    "https://upload.wikimedia.org/wikipedia/en/1/15/First_page_Feludar_Goendagiri.jpg",
    "https://upload.wikimedia.org/wikipedia/en/d/d1/Badshahi_Angti_book_cover.jpg",
    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQX-6RlVxpirfvyg3iMQF3jK1Q-HcoyL5tZSA&s",
    "https://pictures.abebooks.com/isbn/9788177569780-us.jpg",
    "https://upload.wikimedia.org/wikipedia/en/6/6a/Gangtokey_Gondogol_book_cover.jpg",
    "https://upload.wikimedia.org/wikipedia/en/5/56/Sonar_Kella_book_front_cover.jpg",
    "https://upload.wikimedia.org/wikipedia/en/7/70/Baksha_Rahasya_book_cover.jpg",
    "https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/f58b56b2-eb9d-414f-948e-fec2592480d0/de6duxm-f92e2cb3-1e1d-479f-834f-c7aa8905c3d8.jpg/v1/fill/w_1280,h_1811,q_75,strp/samaddarer_chabi_by_shotoavi_de6duxm-fullview.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcL2Y1OGI1NmIyLWViOWQtNDE0Zi05NDhlLWZlYzI1OTI0ODBkMFwvZGU2ZHV4bS1mOTJlMmNiMy0xZTFkLTQ3OWYtODM0Zi1jN2FhODkwNWMzZDguanBnIiwiaGVpZ2h0IjoiPD0xODExIiwid2lkdGgiOiI8PTEyODAifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6aW1hZ2Uud2F0ZXJtYXJrIl0sIndtayI6eyJwYXRoIjoiXC93bVwvZjU4YjU2YjItZWI5ZC00MTRmLTk0OGUtZmVjMjU5MjQ4MGQwXC9zaG90b2F2aS00LnBuZyIsIm9wYWNpdHkiOjk1LCJwcm9wb3J0aW9ucyI6MC40NSwiZ3Jhdml0eSI6ImNlbnRlciJ9fQ.pYSLAOt5pBodtw6EBETWKo88LOPmg2YzXEtxDkLn3Tg",
    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR1bwhIcFqfPji6IM6jeWNmE3eLVaDs7f5uWA&s",
    "https://upload.wikimedia.org/wikipedia/en/d/d3/Royal_Bengal_Rahashya_%28novel%29.jpg",
    "https://ds.rokomari.store/rokomari110/ProductNew20190903/260X372/ef7fcb795_42870.jpg",
    "https://upload.wikimedia.org/wikipedia/en/e/e9/Ghurghutiyar_Ghatona.jpg",
    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTt9K6N4eV27iv4auidC0DL2sch8hOkQkuBEA&s",
    "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1541172264i/34319242.jpg",
    "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1694903207i/148124744.jpg",
    "https://upload.wikimedia.org/wikipedia/en/d/df/Cover_page_of_Chinnamastar_Abhishap.jpg",
    "https://upload.wikimedia.org/wikipedia/en/2/20/First_page_of_Hatyapuri.jpg",
    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSrosAmG7f6DlC9Ru_PLAG1VA5CgUIwZ8k1gg&s",
    "https://ds.rokomari.store/rokomari110/ProductNew20190903/260X372/Joto_Kando_Kathmandute_-Satyajit_Ray-0f0a8-42902.jpg",
    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTsNBs99E8pKgUm1I9sCm3z8-Cu3WlBfhD7cA&s",
    "https://upload.wikimedia.org/wikipedia/en/4/4a/TintorettorJishu.jpg",
    "https://ds.rokomari.store/rokomari110/ProductNew20190903/260X372/Ambor_Sen_Antordhan_Rohossho-Satyajit_Ray-191d6-224150.jpg",
    "https://rukminim1.flixcart.com/image/300/300/book/0/8/0/jahangirer-swarna-mudra-comics-original-imadjbmvyyth9ctp.jpeg",
    "https://m.media-amazon.com/images/I/91ghwBfBbNL._AC_UF1000,1000_QL80_.jpg",
    "https://m.media-amazon.com/images/I/71aApJTNvcL._AC_UF1000,1000_QL80_.jpg",
    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSuaqHQhKTe0DPvuLYGHuZNY7kBoPlVGMRrKQ&s",
    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkYZGk8p1_hl8XnXqQ_8iKh1zYKcqDOoHNmA&s",
    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjmaeZr_0TR96GtFhHswhpJ6DMaY8ICmeIlg&s",
    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTW5gQlZtmta9bUa70NhfpjWOIlWJisb_Vy2Q&s",
    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPpJunxuC13x0GvnvSY2TS-eiMIPA4qK03hg&s",
    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ7M85EVT_szlaRio6OWwo-rzIa10BqidFzmg&s",
    "https://jyotirjagat.wordpress.com/wp-content/uploads/2015/04/satyajit-ray-feluda-dr-munshir-dairy.png?w=648",
    "https://ia801507.us.archive.org/BookReader/BookReaderImages.php?zip=/16/items/dli.scoerat.2291nayanrahasya/dli.scoerat.2291nayanrahasya_jp2.zip&file=dli.scoerat.2291nayanrahasya_jp2/dli.scoerat.2291nayanrahasya_0000.jp2&id=dli.scoerat.2291nayanrahasya&scale=2&rotate=0",
    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNCfduWwUNERytvYqb2PCXaV_558vnSUIVsQ&s",
    "https://upload.wikimedia.org/wikipedia/en/2/21/Feluda_and_Topshe.jpg",
  ];
}